<x-app-layout>
    <x-slot name="header">Food Report</x-slot>
    <div class="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-xs font-black uppercase tracking-wider text-blue-600">{{ $event->title }}</p><h1 class="mt-1 text-3xl font-black">Food distribution report</h1><p class="mt-2 text-sm text-slate-500">Live stock, portions served, manager overrides, and reversals.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('events.meals.report.csv', $event) }}" class="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-extrabold text-white">Download CSV</a><a href="{{ route('events.meals.report.pdf', $event) }}" class="rounded-xl bg-slate-900 px-4 py-3 text-sm font-extrabold text-white">Download PDF</a></div></div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">@foreach([['Stock', $totalStock], ['Currently issued', $totalIssued], ['Wasted', $totalWasted], ['People served', $peopleServed], ['Extra portions', $overrideCount], ['Reversals', $reversalCount]] as [$label, $value])<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-black uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-black">{{ $value }}</p></div>@endforeach</div>

    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Distribution summary</h2></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Distribution</th><th class="p-4">Stock</th><th class="p-4">Issued</th><th class="p-4">Remaining</th><th class="p-4">People</th><th class="p-4">Used</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($meals as $meal)<tr><td class="p-4 font-bold">{{ $meal->name }}</td><td class="p-4">{{ $meal->total_portions }}</td><td class="p-4">{{ $meal->issuedPortions() }}</td><td class="p-4">{{ $meal->remainingPortions() }}</td><td class="p-4">{{ $meal->collections_count }}</td><td class="p-4">{{ $meal->total_portions ? round(($meal->issuedPortions() / $meal->total_portions) * 100) : 0 }}%</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No distributions created.</td></tr>@endforelse</tbody></table></div></section>

    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Forecast vs. confirmed attendance</h2><p class="mt-1 text-xs text-slate-500">Suggested stock = confirmed attendees per category × that category's entitlement.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Distribution</th><th class="p-4">Suggested</th><th class="p-4">Configured stock</th><th class="p-4">Shortfall / surplus</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($forecast as $row)@php $diff = $row['meal']->total_portions - $row['suggested']; @endphp<tr><td class="p-4 font-bold">{{ $row['meal']->name }}</td><td class="p-4">{{ $row['suggested'] }}</td><td class="p-4">{{ $row['meal']->total_portions }}</td><td class="p-4 font-black {{ $diff < 0 ? 'text-red-700' : 'text-emerald-700' }}">{{ $diff >= 0 ? '+' : '' }}{{ $diff }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-slate-500">No distributions created.</td></tr>@endforelse</tbody></table></div></section>

    @if($byStation->isNotEmpty())
    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Portions by station</h2></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Station</th><th class="p-4">Portions issued</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($byStation as $station => $count)<tr><td class="p-4 font-bold">{{ $station }}</td><td class="p-4">{{ $count }}</td></tr>@endforeach</tbody></table></div></section>
    @endif

    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Current collections</h2></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Attendee</th><th class="p-4">Distribution</th><th class="p-4">Station</th><th class="p-4">Portions</th><th class="p-4">Issued by</th><th class="p-4">Last served</th><th class="p-4">Notes</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($collections as $collection)<tr><td class="p-4"><span class="font-bold">{{ $collection->participant->name }}</span><span class="block text-xs text-slate-500">{{ $collection->participant->category ?: 'Unspecified' }}</span>@if($collection->participant->dietary_notes)<span class="block text-xs text-emerald-700">{{ $collection->participant->dietary_notes }}</span>@endif</td><td class="p-4">{{ $collection->distribution->name }}</td><td class="p-4">{{ $collection->station?->name ?: '—' }}</td><td class="p-4 font-black">{{ $collection->quantity }}</td><td class="p-4">{{ $collection->issuer?->name ?: 'Deleted user' }}</td><td class="p-4 whitespace-nowrap">{{ $collection->collected_at?->format('M j, Y g:i A') }}</td><td class="p-4 text-xs {{ $collection->was_overridden ? 'text-amber-700' : 'text-slate-400' }}">{{ $collection->was_overridden ? 'Override: '.$collection->override_reason : 'Standard issue' }}</td></tr>@empty<tr><td colspan="7" class="p-8 text-center text-slate-500">No portions have been issued.</td></tr>@endforelse</tbody></table></div></section>

    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Waste log</h2></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Time</th><th class="p-4">Distribution</th><th class="p-4">Quantity</th><th class="p-4">Reason</th><th class="p-4">Logged by</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($wasteLogs as $log)<tr><td class="p-4 whitespace-nowrap">{{ $log->occurred_at->format('M j, g:i A') }}</td><td class="p-4">{{ $log->distribution->name }}</td><td class="p-4 font-black text-red-700">{{ $log->quantity }}</td><td class="p-4">{{ $log->reason }}</td><td class="p-4">{{ $log->loggedBy?->name ?: 'Deleted user' }}</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-slate-500">No waste logged.</td></tr>@endforelse</tbody></table></div></section>

    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Audit trail</h2><p class="mt-1 text-xs text-slate-500">Permanent history begins with the next serving action.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Time</th><th class="p-4">Action</th><th class="p-4">Attendee</th><th class="p-4">Distribution</th><th class="p-4">Staff</th><th class="p-4">Reason</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($audits as $audit)<tr><td class="p-4 whitespace-nowrap">{{ $audit->occurred_at->format('M j, g:i A') }}</td><td class="p-4 font-black {{ $audit->quantity_change < 0 ? 'text-red-700' : ($audit->action === 'override' ? 'text-amber-700' : 'text-emerald-700') }}">{{ ucfirst($audit->action) }} ({{ $audit->quantity_change > 0 ? '+' : '' }}{{ $audit->quantity_change }})</td><td class="p-4">{{ $audit->participant->name }}</td><td class="p-4">{{ $audit->distribution->name }}</td><td class="p-4">{{ $audit->performer?->name ?: 'Deleted user' }}</td><td class="p-4 text-xs text-slate-500">{{ $audit->reason ?: '—' }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No audit activity yet.</td></tr>@endforelse</tbody></table></div></section>
</x-app-layout>
