<x-app-layout>
    <x-slot name="header">Accommodation Report</x-slot>
    <div class="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-xs font-black uppercase tracking-wider text-blue-600">{{ $event->title }}</p><h1 class="mt-1 text-3xl font-black">Accommodation report</h1><p class="mt-2 text-sm text-slate-500">Occupancy by building, assignment methods, and who still needs following up.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('events.accommodation.index', $event) }}" class="rounded-xl border border-slate-200 px-4 py-3 text-sm font-extrabold text-slate-700">Back to rooms</a><a href="{{ route('events.accommodation.report.csv', $event) }}" class="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-extrabold text-white">Download CSV</a><a href="{{ route('events.accommodation.report.pdf', $event) }}" class="rounded-xl bg-slate-900 px-4 py-3 text-sm font-extrabold text-white">Download PDF</a></div></div>

    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">@foreach([['Beds', $totalBeds], ['Rooms', $totalRooms], ['Need rooms', $requiredCount], ['Allocated', $assignedCount], ['Checked in', $checkedInCount], ['Not checked in', $noShows->count()]] as [$label, $value])<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-black uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-black">{{ $value }}</p></div>@endforeach</div>

    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Occupancy by building &amp; floor</h2></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Location</th><th class="p-4">Rooms</th><th class="p-4">Beds</th><th class="p-4">Occupied</th><th class="p-4">Used</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($occupancy as $label => $row)<tr><td class="p-4 font-bold">{{ $label }}</td><td class="p-4">{{ $row['rooms'] }}</td><td class="p-4">{{ $row['capacity'] }}</td><td class="p-4">{{ $row['occupied'] }}</td><td class="p-4">{{ $row['capacity'] ? round(($row['occupied'] / $row['capacity']) * 100) : 0 }}%</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-slate-500">No rooms set up yet.</td></tr>@endforelse</tbody></table></div></section>

    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Assignment method</h2><p class="mt-1 text-xs text-slate-500">How each currently-assigned attendee got their room.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Method</th><th class="p-4">Attendees</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($methodBreakdown as $method => $count)<tr><td class="p-4 font-bold capitalize">{{ $method }}</td><td class="p-4">{{ $count }}</td></tr>@empty<tr><td colspan="2" class="p-8 text-center text-slate-500">No rooms assigned yet.</td></tr>@endforelse</tbody></table></div></section>

    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Not checked in</h2><p class="mt-1 text-xs text-slate-500">Assigned a room but not yet marked checked in — worth a follow-up if the event has already started.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Attendee</th><th class="p-4">Room</th><th class="p-4">Phone</th><th class="p-4">Email</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($noShows as $registration)<tr><td class="p-4 font-bold">{{ $registration->participant->name }}</td><td class="p-4">{{ $registration->roomAssignment->room->label() }}</td><td class="p-4">{{ $registration->participant->phone ?: '—' }}</td><td class="p-4">{{ $registration->participant->email ?: '—' }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-slate-500">Everyone assigned a room has checked in.</td></tr>@endforelse</tbody></table></div></section>

    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="font-black">Still need a room</h2><p class="mt-1 text-xs text-slate-500">Marked as needing accommodation but not yet assigned.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Attendee</th><th class="p-4">Category</th><th class="p-4">Phone</th><th class="p-4">Email</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($unassigned as $registration)<tr><td class="p-4 font-bold">{{ $registration->participant->name }}</td><td class="p-4">{{ $registration->participant->category ?: 'Unspecified' }}</td><td class="p-4">{{ $registration->participant->phone ?: '—' }}</td><td class="p-4">{{ $registration->participant->email ?: '—' }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-slate-500">Everyone who needs a room has one.</td></tr>@endforelse</tbody></table></div></section>

    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 p-5"><h2 class="font-black">All assignments</h2></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="p-4">Attendee</th><th class="p-4">Room</th><th class="p-4">Status</th><th class="p-4">Method</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($assignments as $assignment)<tr><td class="p-4 font-bold">{{ $assignment->registration->participant->name }}</td><td class="p-4">{{ $assignment->room->label() }}</td><td class="p-4 capitalize">{{ str_replace('_', ' ', $assignment->status) }}{{ $assignment->is_locked ? ' · Locked' : '' }}</td><td class="p-4 capitalize">{{ $assignment->method }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-slate-500">No rooms assigned yet.</td></tr>@endforelse</tbody></table></div></section>
</x-app-layout>
